#!/bin/bash

# Deploy Multi-Admin Whitelist Contract
# This script deploys the whitelist contract with dual admin capabilities

echo "🚀 Deploying Multi-Admin Whitelist Contract..."
echo "📋 Contract will have two admin capabilities:"
echo "   - Deployer address (your current address)"
echo "   - Configured address: 0x0129fc626e3656cfa624cb324826dd5e60782d6f309d11a4450ebde0d974e0a5"
echo ""

# Navigate to contract directory
cd contracts

# Build the contract
echo "🔨 Building contract..."
sui move build

if [ $? -ne 0 ]; then
    echo "❌ Build failed!"
    exit 1
fi

echo "✅ Build successful!"
echo ""

# Deploy the contract
echo "🚀 Deploying contract..."
DEPLOY_OUTPUT=$(sui client publish --gas-budget 100000000 --json)

if [ $? -ne 0 ]; then
    echo "❌ Deployment failed!"
    exit 1
fi

echo "✅ Deployment successful!"
echo ""

# Parse deployment output
PACKAGE_ID=$(echo $DEPLOY_OUTPUT | jq -r '.objectChanges[] | select(.type == "published") | .packageId')
WHITELIST_OBJECT_ID=$(echo $DEPLOY_OUTPUT | jq -r '.objectChanges[] | select(.objectType | contains("Whitelist")) | .objectId')
ADMIN_CAP_IDS=$(echo $DEPLOY_OUTPUT | jq -r '.objectChanges[] | select(.objectType | contains("AdminCap")) | .objectId')

echo "📋 Deployment Results:"
echo "   Package ID: $PACKAGE_ID"
echo "   Whitelist Object ID: $WHITELIST_OBJECT_ID"
echo "   Admin Capability IDs: $ADMIN_CAP_IDS"
echo ""

# Create a config file for the frontend
CONFIG_FILE="../lib/contractConfig.ts"
echo "📝 Creating frontend configuration..."

cat > $CONFIG_FILE << EOF
// Multi-Admin Whitelist Contract Configuration
// Auto-generated by deployment script

export const WHITELIST_CONTRACT_CONFIG = {
  packageId: '$PACKAGE_ID',
  whitelistObjectId: '$WHITELIST_OBJECT_ID',
  // Note: Admin Cap IDs are owned by respective admin addresses
  network: 'testnet',
  adminAddresses: [
    // Deployer address (will be your address)
    // Configured admin address
    '0x0129fc626e3656cfa624cb324826dd5e60782d6f309d11a4450ebde0d974e0a5'
  ]
};

// For backward compatibility
export const CONTRACT_CONFIG = WHITELIST_CONTRACT_CONFIG;
EOF

echo "✅ Configuration saved to: $CONFIG_FILE"
echo ""

echo "🎉 Deployment Complete!"
echo ""
echo "📋 Next Steps:"
echo "   1. Update your frontend to use the new contract configuration"
echo "   2. Both admin addresses can now manage the whitelist"
echo "   3. The configured address (0x0129fc626e3656cfa624cb324826dd5e60782d6f309d11a4450ebde0d974e0a5) has admin access"
echo ""
echo "💡 To test the contract:"
echo "   sui client call --package $PACKAGE_ID --module simple_whitelist --function add_address --args $WHITELIST_OBJECT_ID <ADMIN_CAP_ID> <ADDRESS_TO_WHITELIST>"